server:
  port: 8080
spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k9a308.p.ssafy.io:3306/bookdone_notification?serverTimezone=UTC&characterEncoding=UTF-8&collation=utf8mb4_bin
    username: root
    password: a308a308

    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true

#  redis:
#    port: 6379
#    host: localhost
#    password: null

  kafka:
    admin:
      operations-timeout: 30s
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      auto-offset-reset: earliest
firebase:
  sdk-path: firebase/bookdone-3a0d1-firebase-adminsdk-llxqi-754ac11e18.json

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k9a308.p.ssafy.io:8761/eureka
