server:
  port: 8080
spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookdona_notification?serverTimezone=UTC&characterEncoding=UTF-8&collation=utf8mb4_bin
    username: root
    password: root

  redis:
    port: 6379
    host: localhost
    password: null

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      use_sql_comments: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k9a308.p.ssafy.io:8761/eureka
